version: '3'

services:
  nginx-mao-prm:
    image: nginx:latest
#    image: httpd
    container_name: nginx-mao-prm
    depends_on:
      - engine-mao-prm
    ports:
      - 8001:80
    volumes:
      - $PWD/:/srv/api:rw,cached
      - ./docker/web-client/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - default

  engine-mao-prm:
    image: bitnami/php-fpm
    container_name: engine-mao-prm
    depends_on:
    - mariadb-mao-prm
    volumes:
    - $PWD/:/srv/api:rw,cached
    - $PWD/docker/engine/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
    - ~/.gitconfig:/root/.gitconfig:ro
    - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
    working_dir: /srv/api
    networks:
    - default

  phpmyadmin-mao-prm:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-mao-prm
    depends_on:
    - mariadb-mao-prm
    ports:
    - 8082:80
    environment:
    - PMA_ARBITRARY=1
    - PMA_PORT=3306
    - PMA_HOST=mariadb-mao-prm
    - PMA_USER=root
    - PMA_PASSWORD=dev
    networks:
    - default

  mariadb-mao-prm:
    #    image: percona:5.7
    image: mariadb
    ports:
    - "3309:3306"
    #    container_name: percona-mao
    container_name: mariadb-mao-prm
    environment:
    - "MYSQL_ROOT_PASSWORD=dev"
    - "MYSQL_DATABASE=prm_database"
    - "MYSQL_USER=admin"
    - "MYSQL_PASSWORD=admin"
    networks:
    - default

  web-client:
    image: nginx:latest
#    build: docker/web-client
    container_name: agular-web-client
    working_dir: /var/app
    depends_on:
    - engine-mao-prm
    ports:
    - 4200:80
    volumes:
    - ./WebClient/prm-client/dist:/var/app:rw
    - ./docker/web-client/nginx.conf:/etc/nginx/conf.d/default.conf:rw
    networks:
    - default

volumes:
  db:
    driver: local

networks:
  default:
    external:
      name: docap-api-client-stack

